### ISSUE TITLE
I hope there is punctuation to break sentences

### ISSUE THREAD

**Issue by wp513** [am3n/PersianASR#1]
I hope there is punctuation to break sentences, and Chinese recognition is not accurate

**Comment by wp513** [comment]
Also want to be able to customize the model path, thank you

**Comment by am3n** [comment]
This depends on your model, also this library is prepared with the Persian language model.
For different language model: implement version 1.2.0 & [different-languages](https://github.com/am3n/PersianASR/tree/master?tab=readme-ov-file#different-languages)
